# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
    autofix_prs: true
    autoupdate_schedule: quarterly
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: requirements-txt-fixer
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0  # Use the ref you want to point at
    hooks:
      - id: python-use-type-annotations
      - id: python-no-eval

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [ --py38-plus ]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [ --remove-all-unused-imports, --in-place, --ignore-pass-statements, ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  #  - repo: https://github.com/PyCQA/flake8
  #    rev: 6.1.0
  #    hooks:
  #      - id: flake8
  #        additional_dependencies: [ flake8-bugbear ]
  #        args: [ '--extend-ignore=E402,E501,E201,E202,E203,E221,E225,E231,E261,E266,E302,E305' ]
  #        # additional_dependencies: [ flake8-bugbear, flake8-docstrings ]
  #  - repo: https://github.com/psf/black
  #    rev: 23.10.1
  #    hooks:
  #      - id: black

  #  - repo: https://github.com/codespell-project/codespell
  #    rev: v2.2.4
  #    hooks:

  #      - id: codespell

  #  - repo: https://github.com/pre-commit/mirrors-jshint
  #    rev: v2.13.6  # Use the sha / tag you want to point at
  #    hooks:
  #      - id: jshint

#  - repo: https://github.com/markdownlint/markdownlint
#    rev: 'v0.12.0'
#    hooks:
##      - id: markdownlint
#      - id: markdownlint_docker

#  - repo:  https://github.com/igorshubovych/markdownlint-cli
#    rev: 'v0.37.0'
#    hooks:
#      - id: markdownlint-fix
#  - repo:  https://github.com/jumanjihouse/pre-commit-hooks
#    rev: ''
#    hooks:
#      - id: markdownlint
