[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "boxes"
version = "1.2"
requires-python = ">=3.10"
description = "Boxes generator for laser cutters"
maintainers = [{ name = "Florian Festi", email = "florian@festi.info" }]
readme = "README.rst"
keywords = ["boxes", "box", "generator", "svg", "laser cutter"]
license = "GPL-3.0-or-later"
classifiers = [# https://pypi.python.org/pypi?%3Aaction=list_classifiers
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Environment :: Web Environment",
    "Intended Audience :: Manufacturing",
    "Programming Language :: Python :: 3",
    "Topic :: Multimedia :: Graphics :: Editors :: Vector-Based",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "affine>=2.0",
    "markdown",
    "numpy",
    "PyYAML",
    "qrcode>=7.3.1",
    "rectpack",
    "shapely>=1.8.2",
    "svgpathtools",
    "typing_extensions>=4.5.0",
]

[project.optional-dependencies]
dev = [
  "lxml>=6.0.2",
  "mypy>=2.1.0",
  "pre-commit>=4.6.0",
  "pytest>=9.0.3",
  "types-Markdown"
]
doc = ["sphinx>=8.0.2"]

[project.scripts]
boxes = "boxes.scripts.boxes_main:main"
boxesserver = "boxes.scripts.boxesserver:main"
boxes_proxy = "boxes.scripts.boxes_proxy:main"

[project.urls]
Homepage = "https://hackaday.io/project/10649-boxespy"
Repository = "https://github.com/florianfesti/boxes"
Documentation = "https://florianfesti.github.io/boxes/html/index.html"

[tool.codespell]
ignore-words-list = "ded,te,pathes,reencode,ontop,alledges"

[tool.mypy]
extra_checks = true
ignore_missing_imports = true
strict_equality = true
warn_redundant_casts = true
#warn_return_any = true
warn_no_return = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.rstcheck]
report_level = "ERROR"
ignore_directives = [
    "autoclass",
    "automethod",
    "automodule",
]
ignore_messages = [
  "File referenced in \"include\" directive not found: 'generators.inc'",
]

[tool.ruff]
exclude = ["scripts/*ipynb"]
lint.select = [
    "A", # flake8-builtins
    # "ANN", # flake8-annotations - todo a lot
    "ARG", # flake8-unused-arguments
    "B", # flake8-bugbear
    # "C4",# flake8-comprehensions - todo
    # "C90", # mccabe - not useful
    # "DTZ", # flake8-datetimez - todo
    # "D",# pydocstyle - not useful
    "E", # pycodestyle errors
    # "F",# Pyflakes
    "FA", # flake8-future-annotations
    "FLY", # flynt
    "FURB", # refurb
    "I", # isort
    "ISC", # flake8-implicit-str-concat
    "LOG", # flake8-logging
    # "N", # pep8-naming - not useful
    # "PERF", # Perflint - todo
    "PGH", # pygrep-hooks
    "PIE", # flake8-pie
    "PLC", # pylint convention
    "PLE", # pylint error
    "PLR", # pylint refactor
    # "PLW", # pylint warning - not useful
    "PTH", # flake8-use-pathlib
    "PYI", # flake8-pyi
    # "Q", # flake8-quotes - todo
    # "RET", # flake8-return - todo
    "RSE", # flake8-raise
    "RUF", # Ruff-specific rules
    "S", # flake8-bandit
    # "SIM", # flake8-simplify - not useful
    # "SLF",# flake8-self - not useful
    "SLOT", # flake8-slots
    "T10", # flake8-debugger
    "TC", # flake8-type-checking
    "UP", # pyupgrade
    "W", # pycodestyle warnings
    "YTT", # flake8-2020
]
lint.ignore = [
    "ARG003", # ToDo
    "B006", # ToDo
    "B007", # ToDo
    "B023", # ToDo
    "B904", # ToDo
    "B905", # ToDo
    "C408", # ToDo
    "E402", # ToDo Module level import not at top of file
    "E701", # ToDo Multiple statements on one line (colon)
    "E721", # ToDo Use `is` and `is not` for type comparisons, or `isinstance()` for isinstance checks
    "FURB171", # FixMe
    "LOG015", # ToDo
    "PLC0415", # FixMe
    "PLR1704", # ToDo  Redefining argument with the local name
    "PLR1716", # ToDo  Contains chained boolean comparison that can be simplified
    "PLR1722", # ToDo
    "PLR1730", # ToDo
    "PLR2044", # ToDo Line with empty comment
    "PLR5501", # ToDo
    "RUF015", # ToDo
    "RUF021", # ToDo
    "S101", # ToDo
    "S110", # ToDo
    "S314", # FixMe
    "S603", # ToDo
    "S606", # ToDo
    "UP031", # ToDo
    "A001", # Variable is shadowing a Python builtin
    "A002", # Function argument is shadowing a Python builtin
    "ARG001", # Unused function argument
    "ARG002", # Unused method argument
    "B024", # is an abstract base class, but it has no abstract methods or properties
    "E501", #
    "E712", # Avoid equality comparisons to `True`/`False`; for truth checks
    "E722", # Do not use bare `except`
    "E731", # Do not assign a `lambda` expression, use a `def`
    "E741", #
    "FURB187", # false positive: Use of assignment of `reversed` on list
    "PGH003", # Use specific rule codes when ignoring type issues
    "PIE808", # Unnecessary `start` argument in `range`
    "PLR0911", # Too many return statements
    "PLR0912", # Too many branches
    "PLR0913", # Too many arguments in function definition
    "PLR0915", # Too many statements
    "PLR1714", # Consider merging multiple comparisons
    "PLR2004", # Magic value used in comparison
    "RET504", # Unnecessary assignment before `return` statement
    "RUF005", # Consider instead of concatenation
    "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar`
    "RUF059", # Unpacked variable is never used
    "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
    "TC003", # Move standard library import into a type-checking block
]

[tool.ruff.lint.per-file-ignores]
"boxes/__init__.py" = ["PLC0415"]
"boxes/edges.py" = ["PLC0415"]
"documentation/src/conf.py" = ["DTZ005", "RUF003"]
"setup.py" = ["ALL", "PTH", "S"]
"tests/**/*" = ["S101"]
