name: Static typing hint test

on:
  push:
  pull_request:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  # Build job
  typing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install .[lint]

      - name: mypy version
        run: mypy --version

      - name: Run typing test
        run: |
          mypy ./boxes/
          mypy ./scripts/
          mypy ./documentation/src/boxes2rst.py
